# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grid-layout}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Riethmayer"]
  s.date = %q{2010-02-06}
  s.description = %q{This generator adds 960.gs to your Rails Application. It does a bit more, please have a look at the README.}
  s.email = %q{jan@riethmayer.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "generators/grid_layout_generator.rb",
     "generators/templates/mirror/app/helpers/layout_helper.rb",
     "generators/templates/mirror/app/helpers/meta_helper.rb",
     "generators/templates/mirror/app/views/layouts/application.html.haml",
     "generators/templates/mirror/config/initializers/formtastic.rb",
     "generators/templates/mirror/public/images/12_col.gif",
     "generators/templates/mirror/public/images/16_col.gif",
     "generators/templates/mirror/public/images/24_col.gif",
     "generators/templates/mirror/public/stylesheets/formtastic.css",
     "generators/templates/mirror/public/stylesheets/reset.css",
     "generators/templates/mirror/public/stylesheets/sass/960.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/_all.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_cherry_cheesecake.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_coffee_and_conversation.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_ice_wine_fruit.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_japanese_garden.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_night_in_shining_armor.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_orange_on_olive.sass",
     "generators/templates/mirror/public/stylesheets/sass/_colors/themes/_sir_m.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_footer_elements.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_header_elements.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_login.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_main_content_elements.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_messages.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_navigation.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_search.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_sidebar_elements.sass",
     "generators/templates/mirror/public/stylesheets/sass/_components/_social_apps.sass",
     "generators/templates/mirror/public/stylesheets/sass/_config.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_borders.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_buttons.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_lists.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_misc.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_tables.sass",
     "generators/templates/mirror/public/stylesheets/sass/_core/_typography.sass",
     "generators/templates/mirror/public/stylesheets/sass/formtastic_changes.sass",
     "generators/templates/mirror/public/stylesheets/sass/style.sass",
     "generators/templates/mirror/public/stylesheets/sass/text.sass"
  ]
  s.homepage = %q{http://github.com/riethmayer/grid-layout}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A 960 grid layout generator.}
  s.test_files = [
    "spec/grid_layout_generator_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<generator_extensions>, [">= 0.3.2"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<haml>, [">= 2.3.0"])
    else
      s.add_dependency(%q<generator_extensions>, [">= 0.3.2"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<haml>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<generator_extensions>, [">= 0.3.2"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<haml>, [">= 2.3.0"])
  end
end

